In [1]:
import torch

In [4]:
torch.cuda.is_available()

True

In [6]:
torch.cuda.device_count()

1

In [7]:
torch.cuda.get_device_name(0)

'NVIDIA Graphics Device'

In [23]:
!nvidia-smi

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Sat Jul 15 21:31:42 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA Graphics...  Off  | 00000000:01:00.0  On |                  N/A |
|  0

In [4]:
import torch.nn as nn
import warnings
warnings.filterwarnings("ignore")

In [9]:
dev = torch.device("cuda")

In [10]:
t1 = torch.randn(1,2)

In [11]:
t2 = torch.randn(1,2).to(dev)

In [12]:
print(t1)

tensor([[1.0540, 0.5244]])


In [13]:
print(t2)

tensor([[-0.8685, -0.1440]], device='cuda:0')


In [14]:
t1.is_cuda

False

In [15]:
t2.is_cuda

True

In [3]:
from transformers import pipeline

classifier = pipeline("sentiment-analysis")

/home/kamal/jupyter_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [24]:
classifier("This is one of the best systems in this universe")

[{'label': 'POSITIVE', 'score': 0.9998477697372437}]

In [1]:
model_id = "facebook/opt-350m"

from transformers import AutoModelForCausalLM, AutoTokenizer

/home/kamal/jupyter_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tokenizer = AutoTokenizer.from_pretrained(model_id)

In [3]:
model = AutoModelForCausalLM.from_pretrained(model_id)

In [4]:
text = "Lets do this guys"

In [5]:
encode_text = tokenizer(text=text,return_tensors='pt')

In [40]:
encode_text

{'input_ids': tensor([[   2,  574, 2580,  109,   42, 1669]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

In [6]:
generate_text = model.generate(encode_text['input_ids'],max_new_tokens = 50)

In [44]:
generate_text

tensor([[    2,   574,  2580,   109,    42,  1669,     4, 50118,   100,   437,
           159,     4,    38,   581,    28,    15,    11,    10,   367,   722,
             4,     2]])

In [8]:
decode_text = tokenizer.batch_decode(generate_text)

In [9]:
decode_text

["</s>Lets do this guys.\nI'm down. I'll be on in a few hours.</s>"]

In [11]:
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

In [12]:
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")

In [9]:
tokenizer.mask_token

Using mask_token, but it is not set yet.


In [10]:
sequence = "This is a nice way of learning Transformers" 

In [16]:
encoded_input = tokenizer(
    sequence,
    padding='max_length',
    max_length=512,
    truncation=True,
    return_tensors="pt",
)
decoder_input = tokenizer(
    sequence,
    padding='max_length',
    max_length=512,
    truncation=True,
    return_tensors="pt",
)

In [24]:
encoder_output = model.generate(input_ids=encoded_input["input_ids"], 
                                decoder_input_ids=decoder_input["input_ids"],max_length=613)

In [25]:
output = tokenizer.decode(
    encoder_output[0],
    skip_special_tokens=True
)

In [26]:
output

'This is a nice way of learning Transformers This is a nice way to learn Transformers: The Transformers: The Movie is a great way to learn the history of the Transformers.'