Python Math module is essential for all kinds of programming whether doing Scientific Project, a 
financial application or any other type of programming endeavour. You need math. Period

Math module function is thin wrapper on the underlying C platform's Mathematic Functions. 

Calculating combinations and permutations using factorials

Calculating the height of a pole using trigonometric functions

Calculating radioactive decay using the exponential function

Calculating the curve of a suspension bridge using hyperbolic functions

Solving quadratic equations

Simulating periodic functions, such as sound and light waves, using trigonometric functions

In [1]:
# Constants in the math module

import math

print(math.pi) # The irrational number

print(math.tau) # ratio of circle radius to circumference

print(math.e) # Base of the natural logarithm, used for calculating the growth / decay

print(math.inf) # Representing the boundless or never-ending something mathematically 

# max size in floating point is 1e308

print(math.nan) # representing not a number, when used in algo

3.141592653589793
6.283185307179586
2.718281828459045
inf
nan


In [5]:
# Calculating factorial
import timeit
# learnt to use timeit
timeit.timeit(stmt="math.factorial(7)", setup="import math")

0.1798066999981529

In [10]:
# Calculating Ceiling and Floor

print(math.ceil(6.8))

print(math.floor(8.7))

math.trunc(12.578786)

7
8


12

In [11]:
# Finding closeness, using a threshold

math.isclose(5,5)

True

In [12]:
math.isclose(5,5.1)

False

In [13]:
# close by 20% between each other

math.isclose(6,7,rel_tol=0.2)

True

In [20]:
math.isclose(6.199,6,abs_tol=.2)

True

Power functions have the following formula where the variable x is the base, the variable n is the power, and a can be any constant:

In [22]:
# There are three different Power related function

print(pow(26,6))

print(math.pow(26,6))

print(26 ** 6)

308915776
308915776.0
308915776


### Exponential Function

So what’s so special about exponential functions? The value of the function grows rapidly as the x value increases. If the base is greater than 1, then the function continuously increases in value as x increases.

The Python math module provides a function, exp(), that lets you calculate the **natural exponent** of a number.

In [25]:
print(timeit.timeit("math.e ** 308", setup="import math"))
print(timeit.timeit("pow(math.e, 308)", setup="import math"))
print(timeit.timeit("math.exp(308)", setup="import math"))

0.3785388999967836
0.3443896999997378
0.28340790000220295


### Logarithmic Functions

You can use the natural log in the same way that you use the exponential function. It’s used to calculate values such as the rate of population growth or the rate of radioactive decay in elements.

The Python math module also provides two separate functions that let you calculate the log values to the base of 2 and 10:

log2() is used to calculate the log value to the base 2.

log10() is used to calculate the log value to the base 10.

In [28]:
math.log(10, 2)

3.3219280948873626

In [29]:
math.log(10,10)

1.0

In [30]:
math.log(10, math.e)

2.302585092994046

In [ ]:
math.log()

In [36]:
# Some more functions 

math.gcd(75,125,625)

25

In [38]:
k = 2 + 5j
k

(2+5j)

In [39]:
complex(5,7)

(5+7j)

### Linear Algebra with Python

Its a two part series https://realpython.com/python-scipy-linalg/ and then https://realpython.com/python-linear-algebra/

 scipy.linalg provides tools to study and solve real world problems in an efficient way.

scipy.linalg includes several tools for working with linear algebra problems, including functions for performing matrix calculations, such as determinants, inverses, eigenvalues, eigenvectors, and the singular value decomposition.

In [41]:
import scipy
import numpy as np

Represent matrices and vectors, NumPy uses a special type called ndarray.

In [42]:
A = np.array([[1,2],[3,6],[5,7]])
A

array([[1, 2],
       [3, 6],
       [5, 7]])

In [43]:
# The data type of each element has to be same, else the final data type will be different

A.dtype

dtype('int32')

In [44]:
# Transpose

A.T

array([[1, 3, 5],
       [2, 6, 7]])

In [46]:
A.shape

(3, 2)

In [47]:
v = np.array([[1,2,4]])

v.shape

(1, 3)

In [48]:
v = np.array([[1],[2],[3]])

v.shape

(3, 1)

In [49]:
v = np.array([1,2,3]).reshape(3,1)
v

array([[1],
       [2],
       [3]])

Here, the -1 that you provide as an argument to .reshape() represents the number of rows necessary for the new array to have just one column, as specified by the second argument. In this case, because the original array has three elements, the number of rows for the new array will be 3.

In [50]:
np.array([5,6,8,9,0]).reshape(-1,1)  # -1 will take any number of rows

array([[5],
       [6],
       [8],
       [9],
       [0]])

In [53]:
np.array([[5],[6],[8],[9],[0]]).reshape(1,-1)  # -1 will take any number of cols, and return single columns

array([[5, 6, 8, 9, 0]])

In [54]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [56]:
np.random.rand(2,2) #there is randn method too

array([[0.49098717, 0.79397217],
       [0.52689365, 0.55039863]])

In [58]:
a = 10 * np.ones((2,2))

b = np.array([[2,2],[5,5]])

a * b

array([[20., 20.],
       [50., 50.]])

In [60]:
A = np.array([[1, 2], [3, 4]])
v = np.array([[5], [6]])

In [61]:
A @ v # similar to np.dot(A,v)

array([[17],
       [39]])

In [62]:
# Intro to solving Linear equation from real world 
from scipy import linalg

b = np.array([12,1]).reshape((2,1))

x = linalg.solve(A,b)

x

array([[-23. ],
       [ 17.5]])

What we can solve with linear systems? 

Its when you need to find the proportions of components needed to obtain a certain mixture.

In [65]:
A = np.array([
        [1, 9, 2, 1, 1],
        [10, 1, 2, 1, 1],
        [1, 0, 5, 1, 1],
        [2, 1, 1, 2, 9],
        [2, 1, 2, 13, 2],
])

b = np.array([170, 180, 140, 180, 350]).reshape((5, 1))

linalg.solve(A,b)

array([[10.],
       [10.],
       [20.],
       [20.],
       [10.]])

#### https://realpython.com/python-scipy-linalg/ Completed

#### Started working on [Linear Programming](https://realpython.com/linear-programming-python/)

Linear Programming is set of Mathematical and computational tools that allows you to find a particular solution to this system that corresponds to the maximum or minimum of some other linear function.

Mixed-integer linear programming is an extension of linear programming. It handles problems in which at least one variable takes a discrete integer rather than a continuous value. Although mixed-integer problems look similar to continuous variable problems at first sight, they offer significant advantages in terms of flexibility and precision

Linear programming is the fundamental optimization technique.

During the exploration, there is constant mention of computationally intensive operations required for Linear Programming. The solvers are usually written in C language, on top of python packages are just wrappers. Important
among them is Cpython. Converting the C functions into Python modules and running them inside python is discussed in the below link.  
https://realpython.com/build-python-c-extension-module/

https://docs.python.org/3/extending/extending.html
